# Generated by Django 4.2.4 on 2023-08-18 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextsParsingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=500)),
                ('total_amount', models.PositiveIntegerField()),
                ('parsed_amount', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('average_uniqueness', models.IntegerField()),
                ('average_attempts_to_uniqueness', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('text', models.TextField()),
                ('chat_request', models.TextField()),
                ('uniqueness', models.IntegerField()),
                ('attempts_to_uniqueness', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parsing_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='chatgpt_parser.textsparsingset')),
            ],
        ),
    ]
