# Generated by Django 4.2.4 on 2023-08-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsparsingset',
            name='average_attempts_to_uniqueness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textsparsingset',
            name='average_uniqueness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textsparsingset',
            name='parsed_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textsparsingset',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textsparsingset',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
