# Generated by Django 4.2.4 on 2023-08-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_parser', '0002_alter_textsparsingset_average_attempts_to_uniqueness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsparsingset',
            name='temperature',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
