# Generated by Django 4.2.4 on 2023-08-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_parser', '0003_alter_textsparsingset_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsparsingset',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
