# Generated by Django 4.2.4 on 2023-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_parser', '0004_alter_textsparsingset_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsparsingset',
            name='failed_texts',
            field=models.TextField(null=True),
        ),
    ]
