# Generated by Django 4.2.4 on 2023-09-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_parser', '0006_textsparsingset_low_uniqueness_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsparsingset',
            name='failed_texts',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='textsparsingset',
            name='low_uniqueness_texts',
            field=models.TextField(default=''),
        ),
    ]
