# Generated by Django 4.2.4 on 2023-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_parser', '0007_alter_textsparsingset_failed_texts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsparsingset',
            name='task_strings',
            field=models.TextField(default=''),
        ),
    ]
